name: ðŸ¤–ðŸ¦¾ Run Tests

on:
  pull_request:

jobs:
  run-test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          Functions.Tests.Integration,
          Functions.Tests.Unit,
          Infrastructure.Database.Tests,
          MomentApi.Tests.Integration,
          MomentApi.Tests.Unit,
        ]

    steps:
    - uses: actions/checkout@v4

    # debug
    - run: tree

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Run tests - ${{ matrix.project }}
      run: dotnet test ./src/tests/${{ matrix.project }} -c Release
